### PR TITLE
fix: #1, #7, and investigating a fix for #2

### PR DESCRIPTION
**Pull request by byeoon**
Had to port changes to new version (supercedes #9)

### CODE REVIEW

**Comment by Bims-sh** [comment]
Do we really need the popup, it's pretty annoying imo.
I think the ban/report system we plan in #8 is good.
It also appears on every single github.com page, even those where we don't have any custom css yet.

**Comment by Bims-sh** [comment]
We could show the popup when a user has a lot of reports already, which works after we did the ban/report system

**Comment by byeoon** [comment]
> Do we really need the popup, it's pretty annoying imo. I think the ban/report system we plan in #8 is good. It also appears on every single github.com page, even those where we don't have any custom css yet.

I agree, I like the idea of the report / ban system

**Comment by byeoon** [comment]
Also, did the popup appear twice on every website?

**Comment by Bims-sh** [comment]
> Also, did the popup appear twice on every website?

Didn't notice that happening

**Comment by byeoon** [comment]
> > Also, did the popup appear twice on every website?
> 
> Didn't notice that happening

oh nice i was gonna say it could be because of it being called twice technically
image

**Pull request merged**
